defaultName: Swagger-sample
logging:
  level: ERROR
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
server:
   applicationConnectors: 
     - type: http 
       port: 9000
   adminConnectors: 
     - type: http 
       port: 9071 